apiVersion: v2
name: palworld
version: 0.0.0
description: This chart can provide an rAthena emulator installation on a Kubernetes cluster.
type: application
keywords:
  - palworld
  - server
  - kubernetes
  - helm
home: https://github.com/thijsvanloef/palworld-server-docker
sources:
  - https://github.com/thijsvanloef/palworld-server-docker
maintainers:
  - name: Filipe Souza
    email: filipe.souza@mestre8d.com
    url: https://github.com/Filipe-Souza
icon: https://cdn.akamai.steamstatic.com/steam/apps/1623730/header.jpg
appVersion: "latest"
deprecated: false