{{- if not .Values.server.storage.external }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace }}
  name: "{{ .Release.Name }}-datadir-pvc"
  annotations:
    {{- with .Values.server.config.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: "{{ .Release.Name }}-datadir-pvc"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "{{ .Release.Name }}-datadir-pvc"
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    {{- if .Values.server.storage.preventDelete }}
    helm.sh/resource-policy: keep
    {{ end }}
    {{- with .Values.server.config.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.server.storage.size }}
  storageClassName: {{ .Values.server.storage.storageClassName }}
{{ end }}