---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: palworld-server
  name: palworld-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: palworld-server
  template:
    metadata:
      labels:
        app: palworld-server
    spec:
      containers:
        - name: palworld-server
          image: thijsvanloef/palworld-server-docker:v2.2.2
          # image: ghcr.io/thijsvanloef/palworld-server-docker:v2.2.2 for GitHub Container Registry
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8211
              name: server
              protocol: UDP
            - containerPort: 27015
              name: query
              protocol: UDP
          env:
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: palworld-secrets
                  key: adminPassword
          envFrom:
            - configMapRef:
                name: palworld-cm
          volumeMounts:
            - mountPath: /palworld
              name: datadir
          startupProbe:
            exec:
              command: ["sh", "-c", "pgrep PalServer-Linux >/dev/null"]
            failureThreshold: 120
            periodSeconds: 5
          readinessProbe:
            exec:
              command: ["sh", "-c", "pgrep PalServer-Linux >/dev/null"]
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["sh", "-c", "pgrep PalServer-Linux >/dev/null"]
            periodSeconds: 20
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: palworld-server-datadir
