{{- define "server.rcon.password" -}}
{{- randAlphaNum 24 | nospace -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: "{{ .Release.Name }}-rcon-password"
  annotations:
    {{- with .Values.server.config.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: "{{ .Release.Name }}-rcon-password"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "{{ .Release.Name }}-rcon-password"
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    {{- with .Values.server.config.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  rconPassword: {{- if .Values.server.config.rcon.password }} "{{ .Values.server.config.rcon.password }}" {{ else }} "{{ include "server.rcon.password" .}}" {{ end }}