---
apiVersion: v1
kind: ConfigMap
metadata:
  name: restart-deployment-configmap
data:
  restart-deployment.sh: |
    #!/bin/bash
    cont=$(kubectl -n palworld get pods -o=jsonpath='{.items[?(@.metadata.labels.app=="palworld-server")].metadata.name}')

    function exec_rest_cmd() {
      kubectl exec -n palworld -i pod/$cont -- rest-cli "$@"
    }

    exec_rest_cmd announce "Saving Server Data..."
    exec_rest_cmd save
    sleep 30
    exec_rest_cmd announce "Backing up Server Data..."
    kubectl exec -n palworld -i pod/$cont -- backup
    sleep 30

    step=5
    for i in $(seq 30 -$step 1); do
      exec_rest_cmd announce "Rebooting in $i seconds..."
      sleep $step
    done

    exec_rest_cmd shutdown 1 "now"
    sleep 30
    kubectl -n palworld rollout restart deployment/palworld-server
